FROM node:16-alpine3.18

RUN addgroup backend && adduser -S -G backend backend
USER backend

WORKDIR /app/

COPY --chown=backend package*.json .
COPY --chown=backend . .

run npm i @nestjs/cli@7.6.0

RUN npm run prebuild
RUN npm run build

RUN cp -r env/ ./dist/env
RUN cp -r package.json ./dist/package.json
RUN cp -r i18n/ ./dist/i18n

RUN cd dist
RUN npm install

EXPOSE 9000
EXPOSE 9001
CMD ["npm", "run", "start:docker:prod"]