# Compilar ficheros
FROM node:16-alpine3.18 as build-stage
WORKDIR /app/
COPY package*.json .
RUN npm i @angular/cli@13.1.0
COPY . .
RUN npm run build:prod

# Levantar ficheros compilados
FROM nginx:1.25.1-alpine3.17-slim
COPY --from=build-stage /app/dist/ /usr/share/nginx/html/
EXPOSE 80
CMD ["nginx", "-g", "daemon off;"]